# Generated by Django 3.2 on 2024-01-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="is_editable",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="is_public",
        ),
    ]
