# Generated by Django 3.2 on 2024-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20240104_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
    ]
