# Generated by Django 3.2 on 2024-02-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_accounts_is_external"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="time_zone",
            field=models.CharField(default="UTC", max_length=100),
        ),
    ]
