# Generated by Django 3.2 on 2025-01-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='diary.event'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
