# Generated by Django 3.2 on 2025-01-15 11:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_remove_notes_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anonymous_guests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvailabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(max_length=250)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diary.availability')),
            ],
        ),
    ]
