# Generated by Django 3.2 on 2025-01-16 10:14

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_add_anonymous_guests_field_to_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityevent",
            name="token",
            field=models.CharField(default=diary.models.get_token, max_length=100),
            preserve_default=False,
        ),
    ]
