# Generated by Django 3.2 on 2025-01-17 09:57

import diary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_add_token_to_availability_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('week_before', 'One week before'), ('day_before', 'One day before'), ('12_hours_before', '12 hours before'), ('6_hours_before', '6 hours before'), ('hour_before', 'One hour before'), ('30_minutes_before', '30 minutes before'), ('15_minutes_before', '15 minutes before'), ('minute_before', 'One minute before')], max_length=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='availabilityevent',
            name='token',
            field=models.CharField(default=diary.models.get_token, max_length=100),
        ),
    ]
