# Generated by Django 3.2 on 2025-01-20 07:46

import diary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_create_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=diary.models.get_token, max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='diary.availability')),
            ],
        ),
    ]
