# Generated by Django 3.2 on 2025-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_add_reminders_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
